package:
  format-version: "1.0.0"
  name: "gfx_apps_pic32cx_sg"
  version: "3.0.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "gfx"
      type: "package"
      version: "3.13.0"
    - name: "usb"
      type: "package"
      version: "3.11.0-E1"
    - name: "bsp"
      type: "package"
      version: "v3.16.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.17.0"
    - name: "csp"
      type: "package"
      version: "v3.17.0"
